"""Initial migration

Revision ID: 8ffd8c95288c
Revises: 
Create Date: 2025-06-04 17:37:46.170758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffd8c95288c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=50), nullable=False),
    sa.Column('nazwisko', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('haslo', sa.String(length=128), nullable=False),
    sa.Column('rola', sa.String(length=50), nullable=False),
    sa.Column('aktywny', sa.Boolean(), nullable=True),
    sa.Column('ostatnie_logowanie', sa.DateTime(), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.Column('data_modyfikacji', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lekarz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=50), nullable=False),
    sa.Column('nazwisko', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('haslo', sa.String(length=128), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('specjalizacja', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('numer_pwz', sa.String(length=20), nullable=True),
    sa.Column('zdjecie_url', sa.String(length=255), nullable=True),
    sa.Column('aktywny', sa.Boolean(), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.Column('data_modyfikacji', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('log_systemowy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('akcja', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('uzytkownik_id', sa.Integer(), nullable=True),
    sa.Column('rola_uzytkownika', sa.String(length=50), nullable=True),
    sa.Column('ip_adres', sa.String(length=50), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metoda_platnosci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=50), nullable=False),
    sa.Column('aktywna', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacjent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=50), nullable=False),
    sa.Column('nazwisko', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('haslo', sa.String(length=128), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('data_urodzenia', sa.Date(), nullable=True),
    sa.Column('adres', sa.String(length=200), nullable=True),
    sa.Column('kod_pocztowy', sa.String(length=10), nullable=True),
    sa.Column('miasto', sa.String(length=100), nullable=True),
    sa.Column('kraj', sa.String(length=100), nullable=True),
    sa.Column('pesel', sa.String(length=11), nullable=True),
    sa.Column('aktywny', sa.Boolean(), nullable=True),
    sa.Column('email_zweryfikowany', sa.Boolean(), nullable=True),
    sa.Column('kod_weryfikacyjny', sa.String(length=36), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.Column('data_modyfikacji', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('powiadomienie_konfiguracja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('czas_przed_wizyta', sa.Integer(), nullable=True),
    sa.Column('szablon_email', sa.Text(), nullable=True),
    sa.Column('szablon_sms', sa.String(length=160), nullable=True),
    sa.Column('aktywny', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usluga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('cena', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('czas_trwania', sa.Integer(), nullable=False),
    sa.Column('aktywna', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archiwizacja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('lokalizacja', sa.String(length=255), nullable=True),
    sa.Column('rozmiar', sa.Integer(), nullable=True),
    sa.Column('administrator_id', sa.Integer(), nullable=False),
    sa.Column('data_rozpoczecia', sa.DateTime(), nullable=True),
    sa.Column('data_zakonczenia', sa.DateTime(), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagram_dentystyczny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pacjent_id', sa.Integer(), nullable=False),
    sa.Column('numer_zeba', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('data_modyfikacji', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pacjent_id'], ['pacjent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pacjent_id', 'numer_zeba', name='uq_pacjent_zab')
    )
    op.create_table('platnosc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kwota', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metoda_platnosci_id', sa.Integer(), nullable=True),
    sa.Column('identyfikator_transakcji', sa.String(length=100), nullable=True),
    sa.Column('url_platnosci', sa.String(length=255), nullable=True),
    sa.Column('data_platnosci', sa.DateTime(), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['metoda_platnosci_id'], ['metoda_platnosci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('godzina_od', sa.Time(), nullable=False),
    sa.Column('godzina_do', sa.Time(), nullable=False),
    sa.Column('dostepny', sa.Boolean(), nullable=True),
    sa.Column('lekarz_id', sa.Integer(), nullable=False),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lekarz_id'], ['lekarz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wizyta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pacjent_id', sa.Integer(), nullable=False),
    sa.Column('lekarz_id', sa.Integer(), nullable=False),
    sa.Column('termin_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('platnosc_id', sa.Integer(), nullable=True),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('notatka_wewnetrzna', sa.Text(), nullable=True),
    sa.Column('kod_potwierdzenia', sa.String(length=10), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.Column('data_modyfikacji', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lekarz_id'], ['lekarz.id'], ),
    sa.ForeignKeyConstraint(['pacjent_id'], ['pacjent.id'], ),
    sa.ForeignKeyConstraint(['platnosc_id'], ['platnosc.id'], ),
    sa.ForeignKeyConstraint(['termin_id'], ['termin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wizyta_id', sa.Integer(), nullable=False),
    sa.Column('temat', sa.String(length=255), nullable=False),
    sa.Column('tresc', sa.Text(), nullable=False),
    sa.Column('data_wyslania', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['wizyta_id'], ['wizyta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podsumowanie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wizyta_id', sa.Integer(), nullable=False),
    sa.Column('szczegoly', sa.Text(), nullable=False),
    sa.Column('zalecenia', sa.Text(), nullable=True),
    sa.Column('nastepna_wizyta_zalecana', sa.Boolean(), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wizyta_id'], ['wizyta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recepta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wizyta_id', sa.Integer(), nullable=False),
    sa.Column('kod_recepty', sa.String(length=20), nullable=True),
    sa.Column('identyfikator_p1', sa.String(length=100), nullable=True),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.Column('data_modyfikacji', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wizyta_id'], ['wizyta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wizyta_id', sa.Integer(), nullable=False),
    sa.Column('tresc', sa.String(length=160), nullable=False),
    sa.Column('data_wyslania', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['wizyta_id'], ['wizyta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wizyta_usluga',
    sa.Column('wizyta_id', sa.Integer(), nullable=False),
    sa.Column('usluga_id', sa.Integer(), nullable=False),
    sa.Column('ilosc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usluga_id'], ['usluga.id'], ),
    sa.ForeignKeyConstraint(['wizyta_id'], ['wizyta.id'], ),
    sa.PrimaryKeyConstraint('wizyta_id', 'usluga_id')
    )
    op.create_table('recepta_lek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepta_id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.Column('dawkowanie', sa.String(length=200), nullable=False),
    sa.Column('ilosc', sa.Integer(), nullable=False),
    sa.Column('refundacja', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recepta_id'], ['recepta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recepta_lek')
    op.drop_table('wizyta_usluga')
    op.drop_table('sms')
    op.drop_table('recepta')
    op.drop_table('podsumowanie')
    op.drop_table('email')
    op.drop_table('wizyta')
    op.drop_table('termin')
    op.drop_table('platnosc')
    op.drop_table('diagram_dentystyczny')
    op.drop_table('archiwizacja')
    op.drop_table('usluga')
    op.drop_table('powiadomienie_konfiguracja')
    op.drop_table('pacjent')
    op.drop_table('metoda_platnosci')
    op.drop_table('log_systemowy')
    op.drop_table('lekarz')
    op.drop_table('administrator')
    # ### end Alembic commands ###
