version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemedycyna_backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-telemedycyna}
      - FLASK_ENV=development
      - FLASK_APP=/app/app.py
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-telemedycyna}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-jwt-dev-secret-key}
      - MAIL_SERVER=${MAIL_SERVER:-smtp.example.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-true}
      - MAIL_USE_SSL=${MAIL_USE_SSL:-false}
      - INIT_DB_WITH_SAMPLE_DATA=${INIT_DB_WITH_SAMPLE_DATA:-true}
    volumes:
      - ./app:/app
      - ./app/instance:/app/instance
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - telemedycyna_network

  postgres:
    image: postgres:15-alpine
    container_name: telemedycyna_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-telemedycyna}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-telemedycyna}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - telemedycyna_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: telemedycyna_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-telemedycyna}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - telemedycyna_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./entrypoint.sh:/entrypoint_custom.sh
    entrypoint: /entrypoint_custom.sh
    user: root


networks:
  telemedycyna_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin-data: